### ISSUE TITLE
Syntax Highlighting project for OWL

### ISSUE THREAD

**Issue by CarloDib** [CarloDib/ace#1]
@tillmo
1. added owl to the modelist class so it can be found in the list of Mode when using the kitchen-sink on the localhost to check the code.
2. added 2 classes for the OWL syntax highlighting in the mode folder 

the next steps should be:
1. Make the modifications to the OWL syntax highlighting files.
     a. Highlight the comments.
     b. Remove rdf from the keywords.
     c. Highlight URLs uniformly.
     d. Highlight the prefixed names.

**Comment by tillmo** [comment]
The issue should have a useful headline. Moreover, once you have pushed some code implementing this, please mention the commit here in the issue.

**Comment by CarloDib** [comment]
@tillmo please check my new commit about the first 3 comments and i am still working on the last comment regarding the ' : '

**Comment by CarloDib** [comment]
Dear @tillmo i pushed the last changes on OWL and the last change regarding the colon ':' is done and i tried the code and everything seems to work fine.
