### ISSUE TITLE
Syntax Highlighting for CLIF

### ISSUE THREAD

**Issue by CarloDib** [CarloDib/ace#2]
@tillmo
2. Make the files regarding CLIF syntax highlighting and commit them.

```
   a. Working on the keywords for CLIF
         Only do the reservedtokens, commented sentence and sequence marker since we already gave up on highlighting the name
   b. Do regular expression for the desired keywords and strings wanted to be highlighted
   c. Make final adjustment to finish the code.
```

**Comment by CarloDib** [comment]
Dear @tillmo  i pushed the new classes regarding CLIF highlighting rules, but i have some issues please check and reply to it: 
                  a. I added numbers to the sequence marker because i found something like '...ROW1' in the examples you sent me and i am not sure if that is ok or i should just keep it as letters only.
                  b. Should i highlight strings too just like i did in OWL or it is ok?
Thanks for the help

**Comment by tillmo** [comment]
a. OK
b. yes please
