### ISSUE TITLE
after selection of OWL Manchester syntax, switch to OWL highlighting

### ISSUE THREAD

**Issue by tillmo** [CarloDib/ace#5]
currently, this does not work for me. Do you have an example where it works?

**Comment by CarloDib** [comment]
i pushed 2 files one called 'dol' and in this one i just added the comment section and another one called 'dolall' and in that one i could have highlight every OMS by it's own, but again this is done statically and in case i need to do that dynamically then i have to change a lot of things and write a new coding.... like i should write something which will go through the whole keywords and then check each word by word to see from which logic it is and highlight it depending on that but still it is a problem with the common keywords in each logic and still it would need a bit more coding than normal

**Comment by tillmo** [comment]
no, you definitely should not check the keywords and look which logic they belong to. Instead, you should look for text snippets that change the logic (like `logic OWL2` or `serialization ser:OWL2/Manchester`) and then change the state. Depending on the state, use different syntax highlighters.

**Comment by CarloDib** [comment]
well, i already did that, but i faced a problem. As i remember you told me that you should say something like when it finds the next logic then it should stop highlighting and for that i need to use the snippets which start a logic the same one which close another logic and that could not be done, like for example if "logic OWL2" is the start of  OWL logic then it is the same snippet which say it is the end of the logic before for example in our case there is it DOL then it will not work, at least for now i coudn't find a way to say that. But i am working on it

**Comment by CarloDib** [comment]
And also if you look to the code between owl and clif actually there is nothing i can use to say this is a Dol logic.

**Comment by CarloDib** [comment]
I mean for highlighting the comments from Dol '%%', which they exist after 'serialization ser:CommonLogic'... if those comments from Dol are in Clif then i guess it should be done like said before, it should look for something dynamic which will check word by word or line by line to see where it should go. Anyway right now i guess i can make this work only if i totally understood the code written in the javascript highlighting rules because i feel it can help me to solve this problem.

**Comment by tillmo** [comment]
The idea is to encode the DOL syntax in ACE rules. Since the DOL syntax is context free, regular expressions won't suffice. You need regular expressions plus a stack (which amounts to a pushdown automaton - these provide the same expressive power as regular languages). 

In pararllel, you store the current logic in the state.

Once you have done all this, you know whether you are in DOL or in a specific logic like OWL. This depends on the nonterminal of the context-free DOL grammar. The DOL nonterminal `BasicOMS` indicates logic-specific syntax. In this case, logic-specific hightlighting should be enabled, depending on the current logic (which is stored in the state). The basic OMS ends once a DOL keyword is encountered, and then DOL continues.

**Comment by tillmo** [comment]
OK, I have completely deleted logic selection. The problem is still there, it seems to be related with the occurrence of `import`:
![dolall2](https://cloud.githubusercontent.com/assets/642775/14979166/dbbe24a0-1120-11e6-9661-0d85f0c87df8.png)

**Comment by CarloDib** [comment]
Oh sorry, the problem is with the occurrence of 'PropositionalMereology' because i made it the end of Dol logic.

**Comment by CarloDib** [comment]
I know that i should not say that Dol is end here, but at that time if i didn't specify an end then it will not work since i don't have a stack that i can navigate through it. Now i will work on the stack thing and see if i can get it done by tomorrow.
